strategies:
  vwap_meanrev:
    enabled: false
    name: VWAP_MEANREV
    band_atr_frac: 0.5
    max_session_range_atr_frac: 1.0
    max_open_ext_atr_frac: 0.7
    min_entry_time: "10:00"
    max_entry_time: "15:30"
    trend_cutoff_time: "11:00"
    max_trades_per_day: 1
    stop_band_multiplier: 2.0
    force_debit_spreads: true
